top_srcdir   = /home/osnapdev/postgresql-9.5.5/httpd-2.4.25
top_builddir = /home/osnapdev/postgresql-9.5.5/httpd-2.4.25
srcdir       = /home/osnapdev/postgresql-9.5.5/httpd-2.4.25/modules/cache
builddir     = /home/osnapdev/postgresql-9.5.5/httpd-2.4.25/modules/cache
VPATH        = /home/osnapdev/postgresql-9.5.5/httpd-2.4.25/modules/cache

include $(top_srcdir)/build/special.mk

