top_srcdir   = /home/osnapdev/postgresql-9.5.5/httpd-2.4.25
top_builddir = /home/osnapdev/postgresql-9.5.5/httpd-2.4.25
srcdir       = /home/osnapdev/postgresql-9.5.5/httpd-2.4.25/modules/proxy
builddir     = /home/osnapdev/postgresql-9.5.5/httpd-2.4.25/modules/proxy
VPATH        = /home/osnapdev/postgresql-9.5.5/httpd-2.4.25/modules/proxy
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
#SUBDIRS = balancers
include $(top_srcdir)/build/special.mk
