top_srcdir   = /home/osnapdev/postgresql-9.5.5/httpd-2.4.25
top_builddir = /home/osnapdev/postgresql-9.5.5/httpd-2.4.25
srcdir       = /home/osnapdev/postgresql-9.5.5/httpd-2.4.25/os/unix
builddir     = /home/osnapdev/postgresql-9.5.5/httpd-2.4.25/os/unix
VPATH        = /home/osnapdev/postgresql-9.5.5/httpd-2.4.25/os/unix

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = unixd.c

include $(top_srcdir)/build/ltlib.mk
