top_srcdir   = /home/osnapdev/postgresql-9.5.5/httpd-2.4.25
top_builddir = /home/osnapdev/postgresql-9.5.5/httpd-2.4.25
srcdir       = /home/osnapdev/postgresql-9.5.5/httpd-2.4.25/modules/metadata
builddir     = /home/osnapdev/postgresql-9.5.5/httpd-2.4.25/modules/metadata
VPATH        = /home/osnapdev/postgresql-9.5.5/httpd-2.4.25/modules/metadata

include $(top_srcdir)/build/special.mk

