top_srcdir   = /home/osnapdev/postgresql-9.5.5/httpd-2.4.25
top_builddir = /home/osnapdev/postgresql-9.5.5/httpd-2.4.25
srcdir       = /home/osnapdev/postgresql-9.5.5/httpd-2.4.25/modules
builddir     = /home/osnapdev/postgresql-9.5.5/httpd-2.4.25/modules
VPATH        = /home/osnapdev/postgresql-9.5.5/httpd-2.4.25/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

