top_srcdir   = /home/osnapdev/postgresql-9.5.5/httpd-2.4.25
top_builddir = /home/osnapdev/postgresql-9.5.5/httpd-2.4.25
srcdir       = /home/osnapdev/postgresql-9.5.5/httpd-2.4.25/modules/filters
builddir     = /home/osnapdev/postgresql-9.5.5/httpd-2.4.25/modules/filters
VPATH        = /home/osnapdev/postgresql-9.5.5/httpd-2.4.25/modules/filters

include $(top_srcdir)/build/special.mk

